// All 50 supported languages with metadata
const ALL_LANGUAGES = [
  { code: 'de', label: 'Deutsch', flag: '🇩🇪', rtl: false },
  { code: 'en', label: 'English', flag: '🇬🇧', rtl: false },
  { code: 'es', label: 'Español', flag: '🇪🇸', rtl: false },
  { code: 'fr', label: 'Français', flag: '🇫🇷', rtl: false },
  { code: 'ar', label: 'العربية', flag: '🇸🇦', rtl: true },
  { code: 'pt', label: 'Português', flag: '🇵🇹', rtl: false },
  { code: 'tr', label: 'Türkçe', flag: '🇹🇷', rtl: false },
  { code: 'it', label: 'Italiano', flag: '🇮🇹', rtl: false },
  { code: 'pl', label: 'Polski', flag: '🇵🇱', rtl: false },
  { code: 'bs', label: 'Bosanski', flag: '🇧🇦', rtl: false },
  { code: 'hr', label: 'Hrvatski', flag: '🇭🇷', rtl: false },
  { code: 'sr', label: 'Srpski', flag: '🇷🇸', rtl: false },
  { code: 'cs', label: 'Čeština', flag: '🇨🇿', rtl: false },
  { code: 'sk', label: 'Slovenčina', flag: '🇸🇰', rtl: false },
  { code: 'sl', label: 'Slovenščina', flag: '🇸🇮', rtl: false },
  { code: 'nl', label: 'Nederlands', flag: '🇳🇱', rtl: false },
  { code: 'ru', label: 'Русский', flag: '🇷🇺', rtl: false },
  { code: 'uk', label: 'Українська', flag: '🇺🇦', rtl: false },
  { code: 'ro', label: 'Română', flag: '🇷🇴', rtl: false },
  { code: 'hu', label: 'Magyar', flag: '🇭🇺', rtl: false },
  { code: 'bg', label: 'Български', flag: '🇧🇬', rtl: false },
  { code: 'el', label: 'Ελληνικά', flag: '🇬🇷', rtl: false },
  { code: 'sv', label: 'Svenska', flag: '🇸🇪', rtl: false },
  { code: 'no', label: 'Norsk', flag: '🇳🇴', rtl: false },
  { code: 'da', label: 'Dansk', flag: '🇩🇰', rtl: false },
  { code: 'fi', label: 'Suomi', flag: '🇫🇮', rtl: false },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳', rtl: false },
  { code: 'zh', label: '中文', flag: '🇨🇳', rtl: false },
  { code: 'ja', label: '日本語', flag: '🇯🇵', rtl: false },
  { code: 'ko', label: '한국어', flag: '🇰🇷', rtl: false },
  { code: 'id', label: 'Indonesian', flag: '🇮🇩', rtl: false },
  { code: 'sw', label: 'Kiswahili', flag: '🇰🇪', rtl: false },
  { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳', rtl: false },
  { code: 'th', label: 'ไทย', flag: '🇹🇭', rtl: false },
  { code: 'tl', label: 'Tagalog', flag: '🇵🇭', rtl: false },
  { code: 'af', label: 'Afrikaans', flag: '🇿🇦', rtl: false },
  { code: 'ca', label: 'Català', flag: '🏴', rtl: false },
  { code: 'eu', label: 'Euskara', flag: '🏴', rtl: false },
  { code: 'gl', label: 'Galego', flag: '🏴', rtl: false },
  { code: 'et', label: 'Eesti', flag: '🇪🇪', rtl: false },
  { code: 'lv', label: 'Latviešu', flag: '🇱🇻', rtl: false },
  { code: 'lt', label: 'Lietuvių', flag: '🇱🇹', rtl: false },
  { code: 'mk', label: 'Македонски', flag: '🇲🇰', rtl: false },
  { code: 'sq', label: 'Shqip', flag: '🇦🇱', rtl: false },
  { code: 'be', label: 'Беларуская', flag: '🇧🇾', rtl: false },
  { code: 'kk', label: 'Қазақша', flag: '🇰🇿', rtl: false },
  { code: 'az', label: 'Azərbaycanca', flag: '🇦🇿', rtl: false },
  { code: 'ka', label: 'ქართული', flag: '🇬🇪', rtl: false },
  { code: 'hy', label: 'Հայերեն', flag: '🇦🇲', rtl: false },
  { code: 'he', label: 'עברית', flag: '🇮🇱', rtl: true },
];

// Sorted languages: Deutsch & English first, then separator, then all others alphabetically
const priorityLanguages = ALL_LANGUAGES.filter(l => l.code === 'de' || l.code === 'en');
const otherLanguages = ALL_LANGUAGES.filter(l => l.code !== 'de' && l.code !== 'en')
  .sort((a, b) => a.label.localeCompare(b.label));

export const LANGUAGES = [...priorityLanguages, ...otherLanguages];

// Reply languages for document answer generation (same list with native names)
export const REPLY_LANGUAGES = [
  { code: 'de', label: 'Deutsch' },
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'ar', label: 'العربية' },
  { code: 'pt', label: 'Português' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'it', label: 'Italiano' },
  { code: 'pl', label: 'Polski' },
  { code: 'bs', label: 'Bosanski' },
  { code: 'hr', label: 'Hrvatski' },
  { code: 'sr', label: 'Srpski' },
  { code: 'cs', label: 'Čeština' },
  { code: 'sk', label: 'Slovenčina' },
  { code: 'sl', label: 'Slovenščina' },
  { code: 'nl', label: 'Nederlands' },
  { code: 'ru', label: 'Русский' },
  { code: 'uk', label: 'Українська' },
  { code: 'ro', label: 'Română' },
  { code: 'hu', label: 'Magyar' },
  { code: 'bg', label: 'Български' },
  { code: 'el', label: 'Ελληνικά' },
  { code: 'sv', label: 'Svenska' },
  { code: 'no', label: 'Norsk' },
  { code: 'da', label: 'Dansk' },
  { code: 'fi', label: 'Suomi' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'zh', label: '中文' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
  { code: 'id', label: 'Indonesian' },
  { code: 'sw', label: 'Kiswahili' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'th', label: 'ไทย' },
  { code: 'tl', label: 'Tagalog' },
  { code: 'af', label: 'Afrikaans' },
  { code: 'ca', label: 'Català' },
  { code: 'eu', label: 'Euskara' },
  { code: 'gl', label: 'Galego' },
  { code: 'et', label: 'Eesti' },
  { code: 'lv', label: 'Latviešu' },
  { code: 'lt', label: 'Lietuvių' },
  { code: 'mk', label: 'Македонски' },
  { code: 'sq', label: 'Shqip' },
  { code: 'be', label: 'Беларуская' },
  { code: 'kk', label: 'Қазақша' },
  { code: 'az', label: 'Azərbaycanca' },
  { code: 'ka', label: 'ქართული' },
  { code: 'hy', label: 'Հայերեն' },
  { code: 'he', label: 'עברית' },
];

export const RTL_LANGUAGES = ['ar', 'he'];

export function isRtl(langCode) {
  return RTL_LANGUAGES.includes(langCode);
}
